<<<<<<< HEAD
2016/04/11 09:04:16 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`prestasi`, CONSTRAINT `fk_Log_Employee1` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `prestasi` (`deskripsi`, `jenis`, `tanggal`, `nip_santri`) VALUES (:yp0, :yp1, :yp2, :yp3).
in C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php (73)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 09:04:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`prestasi`, CONSTRAINT `fk_Log_Employee1` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `prestasi` (`deskripsi`, `jenis`, `tanggal`, `nip_santri`) VALUES (:yp0, :yp1, :yp2, :yp3)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\PrestasiController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PrestasiController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prestasi/create')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/prestasi/create
HTTP_REFERER=http://localhost/siadm/index.php/prestasi/create
---
2016/04/11 09:06:44 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`tahun_ajaran`, CONSTRAINT `fk_tajar_matpel` FOREIGN KEY (`id_matpel`) REFERENCES `mata_pelajaran` (`id`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `tahun_ajaran` (`id`, `tahun_ajaran`, `id_matpel`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\TahunAjaranController.php (73)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 09:06:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`tahun_ajaran`, CONSTRAINT `fk_tajar_matpel` FOREIGN KEY (`id_matpel`) REFERENCES `mata_pelajaran` (`id`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `tahun_ajaran` (`id`, `tahun_ajaran`, `id_matpel`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\TahunAjaranController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): TahunAjaranController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('tahunAjaran/cre...')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/tahunAjaran/create
HTTP_REFERER=http://localhost/siadm/index.php/tahunAjaran/create
---
2016/04/11 09:06:54 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`tahun_ajaran`, CONSTRAINT `fk_tajar_matpel` FOREIGN KEY (`id_matpel`) REFERENCES `mata_pelajaran` (`id`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `tahun_ajaran` (`id`, `tahun_ajaran`, `id_matpel`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\TahunAjaranController.php (73)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/11 09:06:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`tahun_ajaran`, CONSTRAINT `fk_tajar_matpel` FOREIGN KEY (`id_matpel`) REFERENCES `mata_pelajaran` (`id`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `tahun_ajaran` (`id`, `tahun_ajaran`, `id_matpel`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\TahunAjaranController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): TahunAjaranController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('tahunAjaran/cre...')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/tahunAjaran/create
HTTP_REFERER=http://localhost/siadm/index.php/tahunAjaran/create
---
=======
2016/04/11 05:11:05 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/11 05:13:44 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/11 05:22:51 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/11 05:27:53 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/11 05:29:21 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/11 05:29:52 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/11 05:30:03 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/11 05:37:27 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/11 18:52:33 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/12 07:01:37 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/12 07:03:36 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/12 07:05:57 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/12 07:06:07 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1460): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(25): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(51): UserIdentity->__construct('admin', 'password')
#9 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#13 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/siadm/
HTTP_REFERER=http://localhost/siadm/
---
2016/04/12 07:35:36 [error] [php] Undefined variable: record (C:\xampp\htdocs\siadm\protected\components\UserIdentity.php:51)
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): LoginForm->validate()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/
in C:\xampp\htdocs\siadm\protected\components\UserIdentity.php (51)
in C:\xampp\htdocs\siadm\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (99)
2016/04/12 07:38:25 [error] [exception.CException] CException: Property "UserIdentity.record" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(51): CComponent->__get('record')
#1 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#5 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(99): CModel->validate()
#6 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#12 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siadm/index.php
HTTP_REFERER=http://localhost/siadm/index.php
---
2016/04/12 07:56:25 [error] [exception.CException] CException: Property "UserWeb.role" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(146): CComponent->__get('role')
#1 C:\xampp\htdocs\siadm\protected\views\layouts\main.php(28): CWebUser->__get('role')
#2 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\yii\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\yii\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\siadm\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#20 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/siadm/index.php/site/index
---
2016/04/12 07:56:25 [error] [exception.CException] CException: Property "UserWeb.role" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(146): CComponent->__get('role')
#1 C:\xampp\htdocs\siadm\protected\views\layouts\main.php(28): CWebUser->__get('role')
#2 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\yii\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\yii\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\siadm\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#20 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/siadm/index.php/site/index
---
2016/04/12 08:00:05 [error] [php] Declaration of Controller::beforeAction() should be compatible with CController::beforeAction($action) (C:\xampp\htdocs\siadm\protected\components\Controller.php:6)
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(3): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(354): require()
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(276): CWebApplication->createController()
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/
in C:\xampp\htdocs\siadm\protected\components\Controller.php (6)
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (3)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/12 08:05:30 [error] [php] Declaration of Controller::beforeAction(CAction $action) should be compatible with CController::beforeAction($action) (C:\xampp\htdocs\siadm\protected\components\Controller.php:6)
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(3): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(354): require()
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(276): CWebApplication->createController()
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/site/login
in C:\xampp\htdocs\siadm\protected\components\Controller.php (6)
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (3)
in C:\xampp\htdocs\siadm\index.php (13)
>>>>>>> master
