2016/04/10 16:36:50 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`riwayat_penyakit`, CONSTRAINT `fk_riwayatpenyakit_santri` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `riwayat_penyakit` (`nip_santri`, `nama_penyakit`, `tanggal`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\RiwayatPenyakitController.php (73)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 16:36:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`riwayat_penyakit`, CONSTRAINT `fk_riwayatpenyakit_santri` FOREIGN KEY (`nip_santri`) REFERENCES `santri` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `riwayat_penyakit` (`nip_santri`, `nama_penyakit`, `tanggal`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\RiwayatPenyakitController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): RiwayatPenyakitController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('riwayatPenyakit...')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php?r=riwayatPenyakit/create
HTTP_REFERER=http://localhost/siadm/index.php?r=riwayatPenyakit/create
---
2016/04/10 14:01:17 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.Nama Pengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CComponent->__get('Nama Pengguna')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(LoginForm), 'Nama Pengguna')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(LoginForm), 'Nama Pengguna', Array)
#3 C:\xampp\htdocs\yii\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(LoginForm), 'Nama Pengguna', Array)
#4 C:\xampp\htdocs\siadm\protected\views\site\login.php(29): CActiveForm->textField(Object(LoginForm), 'Nama Pengguna')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(98): CController->render('login', Array)
#10 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#11 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/siadm/index.php?r=site/login
---
2016/04/10 17:01:15 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (93)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 17:01:15 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.namapengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(58): CComponent->__get('namapengguna')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(LoginForm), 'namapengguna')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/10 17:04:02 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (93)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 17:04:02 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.namapengguna" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(58): CComponent->__get('namapengguna')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(LoginForm), 'namapengguna')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/10 17:17:12 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`pencatatan_pelanggaran`, CONSTRAINT `fk_pp_pelanggaran` FOREIGN KEY (`No_pelanggaran`) REFERENCES `pelanggaran` (`no_pelanggaran`) ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `pencatatan_pelanggaran` (`No_pelanggaran`, `nip_santri`, `id_kesiswaan`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php (73)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 17:17:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`siadmdb`.`pencatatan_pelanggaran`, CONSTRAINT `fk_pp_pelanggaran` FOREIGN KEY (`No_pelanggaran`) REFERENCES `pelanggaran` (`no_pelanggaran`) ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `pencatatan_pelanggaran` (`No_pelanggaran`, `nip_santri`, `id_kesiswaan`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\PencatatanPelanggaranController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): PencatatanPelanggaranController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('pencatatanPelan...')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/pencatatanPelanggaran/create
HTTP_REFERER=http://localhost/siadm/index.php/pencatatanPelanggaran/create
---
2016/04/10 18:32:00 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `role`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\UserController.php (73)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 18:32:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `role`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\UserController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): UserController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/user/create
HTTP_REFERER=http://localhost/siadm/index.php/user/create
---
2016/04/10 18:41:26 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `role`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\UserController.php (73)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 18:41:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `role`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\UserController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): UserController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/user/create
HTTP_REFERER=http://localhost/siadm/index.php/user/create
---
2016/04/10 18:45:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `role`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\siadm\protected\controllers\UserController.php (73)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 18:45:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `role`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\siadm\protected\controllers\UserController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): UserController->actionCreate()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/user/create
HTTP_REFERER=http://localhost/siadm/index.php/user/create
---
2016/04/10 19:36:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('user')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('user')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siadm/index.php/site/user
---
2016/04/10 19:49:46 [error] [exception.CException] exception 'CException' with message 'UserIdentity and its behaviors do not have a method or closure named "beforeAuthentication".' in C:\xampp\htdocs\yii\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(49): CComponent->__call('beforeAuthentic...', Array)
#1 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(49): UserIdentity->beforeAuthentication()
#2 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/10 19:50:01 [error] [exception.CException] exception 'CException' with message 'UserIdentity and its behaviors do not have a method or closure named "beforeAuthentication".' in C:\xampp\htdocs\yii\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(49): CComponent->__call('beforeAuthentic...', Array)
#1 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(49): UserIdentity->beforeAuthentication()
#2 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/10 19:50:13 [error] [exception.CException] exception 'CException' with message 'UserIdentity and its behaviors do not have a method or closure named "beforeAuthentication".' in C:\xampp\htdocs\yii\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(49): CComponent->__call('beforeAuthentic...', Array)
#1 C:\xampp\htdocs\siadm\protected\components\UserIdentity.php(49): UserIdentity->beforeAuthentication()
#2 C:\xampp\htdocs\siadm\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(95): CModel->validate()
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siadm/index.php/site/login
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/10 20:25:45 [error] [php] Declaration of Controller::beforeAction() should be compatible with CController::beforeAction($action) (C:\xampp\htdocs\siadm\protected\components\Controller.php:7)
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(354): require()
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(276): CWebApplication->createController()
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/site/login
in C:\xampp\htdocs\siadm\protected\components\Controller.php (7)
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 20:27:11 [error] [php] Declaration of Controller::beforeAction() should be compatible with CController::beforeAction($action) (C:\xampp\htdocs\siadm\protected\components\Controller.php:7)
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(354): require()
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(276): CWebApplication->createController()
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php/site/login
in C:\xampp\htdocs\siadm\protected\components\Controller.php (7)
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 20:32:22 [error] [php] Declaration of Controller::beforeAction() should be compatible with CController::beforeAction($action) (C:\xampp\htdocs\siadm\protected\components\Controller.php:7)
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(354): require()
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(276): CWebApplication->createController()
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php
in C:\xampp\htdocs\siadm\protected\components\Controller.php (7)
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 20:33:38 [error] [php] Declaration of Controller::beforeAction() should be compatible with CController::beforeAction($action) (C:\xampp\htdocs\siadm\protected\components\Controller.php:7)
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(354): require()
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(276): CWebApplication->createController()
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\siadm\index.php(13): CWebApplication->run()
REQUEST_URI=/siadm/index.php
in C:\xampp\htdocs\siadm\protected\components\Controller.php (7)
in C:\xampp\htdocs\siadm\protected\controllers\SiteController.php (4)
in C:\xampp\htdocs\siadm\index.php (13)
2016/04/10 20:36:28 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.loginurl" is not defined.' in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('loginurl', Array)
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('loginurl', Array)
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\base\CModule.php(103): CModule->getComponent('user')
#4 C:\xampp\htdocs\siadm\protected\views\layouts\main.php(39): CModule->__get('user')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\siadm\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#14 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#16 C:\xampp\htdocs\siadm\protected\controllers\SiteController.php(32): CController->render('index')
#17 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#24 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/siadm/index.php
HTTP_REFERER=http://localhost/siadm/index.php/site/login
---
2016/04/11 01:05:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\siadm\protected\controllers\UserController.php:157
Stack trace:
#0 C:\xampp\htdocs\siadm\protected\controllers\UserController.php(55): UserController->loadModel('4')
#1 [internal function]: UserController->actionView('4')
#2 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UserController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('user/view')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siadm/index.php/user/4
HTTP_REFERER=http://localhost/siadm/index.php/user/update/4
---
2016/04/11 02:00:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('user')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('user')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siadm\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siadm/index.php/site/user
---
